using System;

namespace KCV
{
	public enum PrefabFileInfos
	{
		PREFAB_FILE_INFOS_ID_ST,
		PREFAB_FILE_INFOS_ID_BEF = -1,
		PortTopMainMenu3D,
		PortTopArsenalSelectScene,
		BattleFieldCamera,
		BattleFieldDimCamera,
		ResultShipInfo,
		ResultEShipInfo,
		BattleShipBanner,
		BattleShip,
		BattleField,
		BattleProdDetectionCutIn,
		BattleProdDetectionResultCutIn,
		BattleProdDetectionCloud,
		BattleProdAerialCutin,
		BattleProdAerialCombatP1,
		BattleProdAerialCombatP2,
		BattleProdAerialCombatCutIn,
		BattleProdAerialCombatPhase2,
		BattleProdAerialTorpedo,
		AerialControlProd,
		BattleProdAerialSecondCutIn,
		BattleSupportingShell,
		BattleSupportingAerial,
		BattleSupportingTorpedo,
		BattleProdShellingSlot,
		BattleProdShellingSlotNameNormalAttack,
		BattleProdShellingShipNormalAttack,
		BattleProdShipStatusInfo,
		BattleProdAircraftAttack,
		BattleProdShellingFormationJudge,
		BattleProdObservedShellingCutIn,
		NightMessageProd,
		BattleProdTranscendenceCutIn,
		BattleProdFlagshipWreck,
		BattleProdCenterLine,
		BattleFlightText,
		BattleProdDamageCutIn,
		BattleProdSinking,
		BattleProdWithdrawalDecisionSelection,
		BattleProdBattleFinish,
		BattleProdWinRankJudge,
		BattleResultInformation,
		BattleUIMvp,
		RewardGet,
		BattleProdEscortShipEvacuation,
		BattleProdAdvancingWithDrawalSelect,
		BattleProdAdvancingWithDrawalDC,
		Moderate3DText,
		Heavy3DText,
		UICircleHPGauge,
		UICircleHPGauges,
		Option,
		ShipGet,
		MapClear,
		Thalassocracy,
		MapOpen,
		CommonProdReceiveShip,
		CommonProdBattleReceiveShip,
		CommonProdCutReceiveShip,
		CommonProdReceiveItem,
		CommonProdRevampReceiveItem,
		ISUICategoryList,
		ISUICategoryAreaButton,
		PREFAB_FILE_INFOS_ID_AFT,
		PREFAB_FILE_INFOS_ID_NUM = 62,
		PREFAB_FILE_INFOS_ID_ED = 61
	}
}
