using System;

namespace KCV
{
	public static class SEFIleInfosExtension
	{
		public static string SEFileName(this SEFIleInfos info)
		{
			switch (info)
			{
			case SEFIleInfos.SE_901:
				return "SE_901";
			case SEFIleInfos.SE_902:
				return "SE_902";
			case SEFIleInfos.SE_903:
				return "SE_903";
			case SEFIleInfos.SE_904:
				return "SE_904";
			case SEFIleInfos.SE_905:
				return "SE_905";
			case SEFIleInfos.SE_906:
				return "SE_906";
			case SEFIleInfos.SE_907:
				return "SE_907";
			case SEFIleInfos.SE_908:
				return "SE_908";
			case SEFIleInfos.SE_909:
				return "SE_909";
			case SEFIleInfos.SE_910:
				return "SE_910";
			case SEFIleInfos.SE_911:
				return "SE_911";
			case SEFIleInfos.SE_912:
				return "SE_912";
			case SEFIleInfos.SE_913:
				return "SE_913";
			case SEFIleInfos.SE_914:
				return "SE_914";
			case SEFIleInfos.SE_915:
				return "SE_915";
			case SEFIleInfos.SE_916:
				return "SE_916";
			case SEFIleInfos.SE_917:
				return "SE_917";
			case SEFIleInfos.SE_918:
				return "SE_918";
			case SEFIleInfos.SE_919:
				return "SE_919";
			case SEFIleInfos.SE_920:
				return "SE_920";
			case SEFIleInfos.SE_921:
				return "SE_921";
			case (SEFIleInfos)922:
			case (SEFIleInfos)923:
			case (SEFIleInfos)924:
			case (SEFIleInfos)927:
			case (SEFIleInfos)928:
			case (SEFIleInfos)929:
			case (SEFIleInfos)937:
			case (SEFIleInfos)938:
			case (SEFIleInfos)947:
			case (SEFIleInfos)948:
			case (SEFIleInfos)949:
			case (SEFIleInfos)950:
			case (SEFIleInfos)951:
			case (SEFIleInfos)952:
			case (SEFIleInfos)953:
			case (SEFIleInfos)954:
			case (SEFIleInfos)955:
			case (SEFIleInfos)956:
			case (SEFIleInfos)957:
			case (SEFIleInfos)958:
			case (SEFIleInfos)959:
			case (SEFIleInfos)960:
			case (SEFIleInfos)961:
			case (SEFIleInfos)962:
			case (SEFIleInfos)963:
			case (SEFIleInfos)964:
			case (SEFIleInfos)965:
			case (SEFIleInfos)966:
			case (SEFIleInfos)967:
			case (SEFIleInfos)968:
			case (SEFIleInfos)969:
			case (SEFIleInfos)970:
			case (SEFIleInfos)971:
			case (SEFIleInfos)972:
			case (SEFIleInfos)973:
			case (SEFIleInfos)974:
			case (SEFIleInfos)975:
			case (SEFIleInfos)976:
			case (SEFIleInfos)977:
			case (SEFIleInfos)978:
			case (SEFIleInfos)979:
			case (SEFIleInfos)980:
			case (SEFIleInfos)981:
			case (SEFIleInfos)982:
			case (SEFIleInfos)983:
			case (SEFIleInfos)984:
			case (SEFIleInfos)985:
			case (SEFIleInfos)986:
			case (SEFIleInfos)987:
			case (SEFIleInfos)988:
			case (SEFIleInfos)989:
			case (SEFIleInfos)990:
			case (SEFIleInfos)991:
			case (SEFIleInfos)992:
			case (SEFIleInfos)993:
			case (SEFIleInfos)994:
			case (SEFIleInfos)995:
			case (SEFIleInfos)996:
			case (SEFIleInfos)997:
			case (SEFIleInfos)998:
			case SEFIleInfos.Repair_ShortCrane:
				IL_23A:
				switch (info)
				{
				case SEFIleInfos.SE_001:
					return "SE_001";
				case SEFIleInfos.SE_002:
					return "SE_002";
				case SEFIleInfos.SE_003:
					return "SE_003";
				case SEFIleInfos.SE_004:
					return "SE_004";
				case SEFIleInfos.SE_005:
					return "SE_005";
				case SEFIleInfos.SE_006:
					return "SE_006";
				case SEFIleInfos.SE_007:
					return "SE_007";
				case SEFIleInfos.SE_008:
					return "SE_008";
				case SEFIleInfos.SE_009:
					return "SE_009";
				case SEFIleInfos.SE_010:
					return "SE_010";
				case SEFIleInfos.SE_011:
					return "SE_011";
				case SEFIleInfos.SE_012:
					return "SE_012";
				case SEFIleInfos.SE_013:
					return "SE_013";
				case SEFIleInfos.SE_014:
					return "SE_014";
				case SEFIleInfos.SE_015:
					return "SE_015";
				case SEFIleInfos.SE_016:
					return "SE_016";
				case SEFIleInfos.SE_017:
					return "SE_017";
				case SEFIleInfos.SE_018:
					return "SE_018";
				case SEFIleInfos.SE_019:
					return "SE_019";
				case SEFIleInfos.SE_020:
					return "SE_020";
				case SEFIleInfos.SE_021:
					return "SE_021";
				case SEFIleInfos.SE_022:
					return "SE_022";
				case SEFIleInfos.SE_023:
					return "SE_023";
				case SEFIleInfos.SE_024:
					return "SE_024";
				case SEFIleInfos.SE_025:
					return "SE_025";
				case SEFIleInfos.SE_026:
					return "SE_026";
				case SEFIleInfos.SE_027:
					return "SE_027";
				case SEFIleInfos.SE_028:
					return "SE_028";
				case SEFIleInfos.SE_029:
					return "SE_029";
				case SEFIleInfos.SE_030:
					return "SE_030";
				case SEFIleInfos.SE_031:
					return "SE_031";
				case SEFIleInfos.SE_032:
					return "SE_032";
				case SEFIleInfos.SE_033:
					return "SE_033";
				case SEFIleInfos.SE_034:
					return "SE_034";
				case SEFIleInfos.SE_035:
					return "SE_035";
				case SEFIleInfos.SE_036:
					return "SE_036";
				case SEFIleInfos.SE_037:
					return "SE_037";
				case SEFIleInfos.SE_038:
					return "SE_038";
				case SEFIleInfos.SE_039:
					return "SE_039";
				case SEFIleInfos.SE_040:
					return "SE_040";
				case SEFIleInfos.SE_041:
					return "SE_041";
				case SEFIleInfos.SE_042:
					return "SE_042";
				case SEFIleInfos.SE_043:
					return "SE_043";
				case SEFIleInfos.SE_044:
					return "SE_044";
				case SEFIleInfos.SE_045:
					return "SE_045";
				case SEFIleInfos.SE_046:
					return "SE_046";
				case SEFIleInfos.SE_047:
					return "SE_047";
				case SEFIleInfos.SE_048:
					return "SE_048";
				case SEFIleInfos.SE_049:
					return "SE_049";
				case SEFIleInfos.SE_050:
					return "SE_050";
				case SEFIleInfos.SE_051:
					return "SE_051";
				case SEFIleInfos.SE_052:
					return "SE_052";
				case SEFIleInfos.SE_053:
					return "SE_053";
				case SEFIleInfos.SE_054:
					return "SE_054";
				case SEFIleInfos.SE_055:
					return "SE_055";
				case SEFIleInfos.SE_056:
					return "SE_056";
				case SEFIleInfos.SE_057:
					return "SE_057";
				case SEFIleInfos.SE_058:
					return "SE_058";
				default:
					if (info == SEFIleInfos.SE_926a)
					{
						return "SE_926a";
					}
					if (info == SEFIleInfos.SE_926b)
					{
						return "SE_926b";
					}
					if (info == SEFIleInfos.SE_927a)
					{
						return "SE_927a";
					}
					if (info == SEFIleInfos.SE_927b)
					{
						return "SE_927b";
					}
					if (info != SEFIleInfos.SE_939b)
					{
						return string.Empty;
					}
					return "SE_939b";
				}
				break;
			case SEFIleInfos.SE_925:
				return "SE_925";
			case SEFIleInfos.SE_926:
				return "SE_926";
			case SEFIleInfos.SE_930:
				return "SE_930";
			case SEFIleInfos.SE_931:
				return "SE_931";
			case SEFIleInfos.SE_932:
				return "SE_932";
			case SEFIleInfos.SE_933:
				return "SE_933";
			case SEFIleInfos.SE_934:
				return "SE_934";
			case SEFIleInfos.SE_935:
				return "SE_935";
			case SEFIleInfos.SE_936:
				return "SE_936";
			case SEFIleInfos.SE_939a:
				return "SE_939a";
			case SEFIleInfos.SE_940:
				return "SE_940";
			case SEFIleInfos.SE_941:
				return "SE_941";
			case SEFIleInfos.SE_942:
				return "SE_942";
			case SEFIleInfos.SE_943:
				return "SE_943";
			case SEFIleInfos.SE_944:
				return "SE_944";
			case SEFIleInfos.SE_945:
				return "SE_945";
			case SEFIleInfos.SE_946:
				return "SE_946";
			case SEFIleInfos.SE_999:
				return "SE_999";
			case SEFIleInfos.Click:
				return "Click";
			case SEFIleInfos.CommonEnter1:
				return "Common/Enter1";
			case SEFIleInfos.CommonEnter2:
				return "Common/Enter2";
			case SEFIleInfos.CommonEnter3:
				return "Common/Enter3";
			case SEFIleInfos.CommonCursolMove:
				return "Common/CursolMove";
			case SEFIleInfos.CommonCursolMove2:
				return "Common/CursolMove2";
			case SEFIleInfos.CommonCancel1:
				return "Common/Cancel1";
			case SEFIleInfos.CommonCancel2:
				return "Common/Cancel2";
			case SEFIleInfos.CommonRemove:
				return "Common/Remove";
			case SEFIleInfos.CommonWrong:
				return "Common/Wrong";
			case SEFIleInfos.MainMenuSetHex:
				return "PortTop/MainMenuSetHex";
			case SEFIleInfos.MainMenuOnMouse:
				return "PortTop/MainMenuOnMouse";
			case SEFIleInfos.MainMenuOnClick:
				return "PortTop/MainMenuOnClick";
			case SEFIleInfos.MainMenuHexZoom:
				return "PortTop/MainMenuHexZoom";
			case SEFIleInfos.StrategyShipMove:
				return "Strategy/ShipMove";
			case SEFIleInfos.Trumpet1:
				return "Strategy/Trumpet1";
			case SEFIleInfos.Keihou:
				return "Strategy/Keihou";
			case SEFIleInfos.EnemyComming:
				return "Strategy/EnemyComming";
			case SEFIleInfos.IA_Failure:
				return "ImprovementArsenal/IA_Failure";
			case SEFIleInfos.IA_Spark:
				return "ImprovementArsenal/IA_Spark";
			case SEFIleInfos.IA_Success1:
				return "ImprovementArsenal/IA_Success1";
			case SEFIleInfos.IA_Success2:
				return "ImprovementArsenal/IA_Success2";
			case SEFIleInfos.Revamp_Yousetu:
				return "ImprovementArsenal/aks_yousetu";
			case SEFIleInfos.BattleShellingSlide:
				return "Battle/ShellingSlide";
			case SEFIleInfos.BattleTorpedo:
				return "Battle/Torpedo";
			case SEFIleInfos.BattleCenterLineOpen:
				return "Battle/CenterLineOpen";
			case SEFIleInfos.BattleDamage:
				return "Battle/Damage";
			case SEFIleInfos.BattleAdmission:
				return "Battle/Admission";
			case SEFIleInfos.BattleTookOffAircraft:
				return "Battle/TookOffAircraft";
			case SEFIleInfos.BattleNightMessage:
				return "Battle/NightMessage";
			case SEFIleInfos.FanfareS:
				return "Battle/Fanfare/FanfareS";
			case SEFIleInfos.FanfareA:
				return "Battle/Fanfare/FanfareA";
			case SEFIleInfos.FanfareB:
				return "Battle/Fanfare/FanfareB";
			case SEFIleInfos.FanfareE:
				return "Battle/Fanfare/FanfareE";
			case SEFIleInfos.ClearAA:
				return "Battle/ClearAA";
			case SEFIleInfos.ClearAAA:
				return "Battle/ClearAAA";
			case SEFIleInfos.RewardGet:
				return "Battle/RewardGet";
			case SEFIleInfos.RewardGet2:
				return "Battle/RewardGet2";
			case SEFIleInfos.Explode:
				return "SE_045";
			}
			goto IL_23A;
		}
	}
}
