using System;

namespace KCV.Remodel
{
	public enum ScreenStatus
	{
		SELECT_DECK_SHIP,
		SELECT_OTHER_SHIP,
		SELECT_SETTING_MODE,
		MODE_SOUBI_HENKOU,
		MODE_SOUBI_HENKOU_TYPE_SELECT,
		MODE_SOUBI_HENKOU_ITEM_SELECT,
		MODE_SOUBI_HENKOU_PREVIEW,
		MODE_KINDAIKA_KAISHU,
		MODE_KINDAIKA_KAISHU_SOZAI_SENTAKU,
		MODE_KINDAIKA_KAISHU_KAKUNIN,
		MODE_KINDAIKA_KAISHU_ANIMATION,
		MODE_KINDAIKA_KAISHU_END_ANIMATION,
		MODE_KAIZO,
		MODE_KAIZO_ANIMATION,
		MODE_KAIZO_END_ANIMATION,
		WAIT
	}
}
